-- คนที่ 1: ผู้ใช้และ profile (One-to-One)

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('STUDENT', 'LECTURER', 'STAFF', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE user_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    full_name    VARCHAR(150) NOT NULL,
    student_code VARCHAR(20),
    phone        VARCHAR(20),
    department   VARCHAR(150),
    CONSTRAINT uk_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ผู้ใช้ทดสอบครบทุก role รหัสผ่านทุกบัญชีคือ Password123!
INSERT INTO users (email, password_hash, role, status) VALUES
    ('admin@kkumail.com',    '$2a$10$Hqr5s7oysYzET9m38zw0y.qwkSazZ0txRmwwo6RDQlCPhour2dxG.', 'ADMIN',    'ACTIVE'),
    ('staff@kkumail.com',    '$2a$10$Hqr5s7oysYzET9m38zw0y.qwkSazZ0txRmwwo6RDQlCPhour2dxG.', 'STAFF',    'ACTIVE'),
    ('lecturer@kkumail.com', '$2a$10$Hqr5s7oysYzET9m38zw0y.qwkSazZ0txRmwwo6RDQlCPhour2dxG.', 'LECTURER', 'ACTIVE'),
    ('student@kkumail.com',  '$2a$10$Hqr5s7oysYzET9m38zw0y.qwkSazZ0txRmwwo6RDQlCPhour2dxG.', 'STUDENT',  'ACTIVE'),
    ('student2@kkumail.com', '$2a$10$Hqr5s7oysYzET9m38zw0y.qwkSazZ0txRmwwo6RDQlCPhour2dxG.', 'STUDENT',  'ACTIVE');

INSERT INTO user_profiles (user_id, full_name, student_code, phone, department)
SELECT id, 'ผู้ดูแลระบบ', NULL, '043009700', 'วิทยาลัยการคอมพิวเตอร์' FROM users WHERE email = 'admin@kkumail.com';

INSERT INTO user_profiles (user_id, full_name, student_code, phone, department)
SELECT id, 'เจ้าหน้าที่ อาคาร SC09', NULL, '043009701', 'วิทยาลัยการคอมพิวเตอร์' FROM users WHERE email = 'staff@kkumail.com';

INSERT INTO user_profiles (user_id, full_name, student_code, phone, department)
SELECT id, 'อาจารย์ ทดสอบ ระบบจอง', NULL, '0812345678', 'สาขาวิทยาการคอมพิวเตอร์' FROM users WHERE email = 'lecturer@kkumail.com';

INSERT INTO user_profiles (user_id, full_name, student_code, phone, department)
SELECT id, 'นักศึกษา ทดสอบ หนึ่ง', '6733800001', '0898765432', 'สาขาวิทยาการคอมพิวเตอร์' FROM users WHERE email = 'student@kkumail.com';

INSERT INTO user_profiles (user_id, full_name, student_code, phone, department)
SELECT id, 'นักศึกษา ทดสอบ สอง', '6733800002', '0891112222', 'สาขาเทคโนโลยีสารสนเทศ' FROM users WHERE email = 'student2@kkumail.com';
