-- คนที่ 2: ห้อง ประเภทห้อง อุปกรณ์ (Many-to-Many ผ่าน room_equipment) และช่วงปิดห้อง

CREATE TABLE room_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_room_types_name UNIQUE (name)
);

CREATE TABLE rooms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(20)  NOT NULL,
    name         VARCHAR(150) NOT NULL,
    floor        INTEGER      NOT NULL,
    capacity     INTEGER      NOT NULL,
    description  VARCHAR(500),
    room_type_id BIGINT       NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rooms_code UNIQUE (code),
    CONSTRAINT fk_rooms_room_type FOREIGN KEY (room_type_id) REFERENCES room_types (id),
    CONSTRAINT ck_rooms_capacity CHECK (capacity > 0),
    CONSTRAINT ck_rooms_status CHECK (status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE'))
);

CREATE INDEX idx_rooms_room_type ON rooms (room_type_id);
CREATE INDEX idx_rooms_floor ON rooms (floor);

CREATE TABLE equipment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_equipment_name UNIQUE (name)
);

-- ตารางเชื่อม M:N มีจำนวนอุปกรณ์ (quantity) ลบห้องหรืออุปกรณ์แล้วแถวเชื่อมถูกลบตาม
CREATE TABLE room_equipment (
    room_id      BIGINT  NOT NULL,
    equipment_id BIGINT  NOT NULL,
    quantity     INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT pk_room_equipment PRIMARY KEY (room_id, equipment_id),
    CONSTRAINT fk_room_equipment_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_room_equipment_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT ck_room_equipment_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_room_equipment_equipment ON room_equipment (equipment_id);

CREATE TABLE room_closures (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT       NOT NULL,
    start_time TIMESTAMP    NOT NULL,
    end_time   TIMESTAMP    NOT NULL,
    reason     VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_room_closures_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    CONSTRAINT ck_room_closures_time CHECK (end_time > start_time)
);

CREATE INDEX idx_room_closures_room_start ON room_closures (room_id, start_time);

-- ===== Seed data =====
-- รหัสห้อง ชื่อ ชั้น และประเภท มาจากผังอาคาร SC09 (SC09_College_of_Computing_combined.json, 2026-10-07)
-- TODO(คนที่ 2): ความจุ (capacity) และอุปกรณ์ในห้องเป็นค่าประมาณ ยังไม่มีข้อมูลจริง ตรวจและแก้ให้ตรงก่อน deploy

INSERT INTO room_types (name, description) VALUES
    ('ห้องบรรยาย', 'ห้องเรียนบรรยายพร้อมโปรเจกเตอร์'),
    ('ห้องปฏิบัติการคอมพิวเตอร์', 'ห้องแล็บที่มีเครื่องคอมพิวเตอร์ประจำที่นั่ง'),
    ('ห้องประชุม', 'ห้องประชุมขนาดเล็กถึงกลาง'),
    ('ห้องโถงอเนกประสงค์', 'ห้องโถงสำหรับกิจกรรมอเนกประสงค์');

INSERT INTO equipment (name, description) VALUES
    ('โปรเจกเตอร์', 'เครื่องฉายภาพพร้อมจอ'),
    ('คอมพิวเตอร์', 'เครื่องคอมพิวเตอร์ตั้งโต๊ะ'),
    ('ไวท์บอร์ด', 'กระดานไวท์บอร์ด'),
    ('ไมโครโฟน', 'ไมโครโฟนไร้สายพร้อมลำโพง'),
    ('Smart TV', 'จอทีวีสำหรับแสดงผลจากโน้ตบุ๊ก');

-- ชั้น 1
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-CP9127', 'ห้องโถง CP9127', 1, 200, 'ห้องโถงชั้น 1', id, 'ACTIVE' FROM room_types WHERE name = 'ห้องโถงอเนกประสงค์';

-- ชั้น 2
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9226', 'LAB 9226', 2, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9227', 'LAB 9227', 2, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9228', 'LAB 9228', 2, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9230', 'ห้องเรียน 9230', 2, 20, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องบรรยาย';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9231', 'ห้องประชุม 9231', 2, 10, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องประชุม';

-- ชั้น 4
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9421', 'LAB 9421', 4, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9422', 'LAB 9422', 4, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9427', 'ห้องเรียน 9427', 4, 20, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องบรรยาย';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9428', 'ห้องประชุม 9428', 4, 10, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องประชุม';

-- ชั้น 5
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9524', 'LAB NETWORK 9524', 5, 30, 'ห้องปฏิบัติการเครือข่าย', id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9525', 'LAB 9525', 5, 40, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องปฏิบัติการคอมพิวเตอร์';
INSERT INTO rooms (code, name, floor, capacity, description, room_type_id, status)
SELECT 'SC09-9527', 'ห้องเรียน 9527', 5, 20, NULL, id, 'ACTIVE' FROM room_types WHERE name = 'ห้องบรรยาย';


-- อุปกรณ์ในแต่ละห้อง (ค่าประมาณตามประเภทห้อง ยังไม่มีข้อมูลจริง)
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-CP9127' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 2 FROM rooms r, equipment e WHERE r.code = 'SC09-CP9127' AND e.name = 'ไมโครโฟน';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9226' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9226' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9227' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9227' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9228' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9228' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9230' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9230' AND e.name = 'ไวท์บอร์ด';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9231' AND e.name = 'Smart TV';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9231' AND e.name = 'ไวท์บอร์ด';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9421' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9421' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9422' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9422' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9427' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9427' AND e.name = 'ไวท์บอร์ด';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9428' AND e.name = 'Smart TV';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9428' AND e.name = 'ไวท์บอร์ด';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 30 FROM rooms r, equipment e WHERE r.code = 'SC09-9524' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9524' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 40 FROM rooms r, equipment e WHERE r.code = 'SC09-9525' AND e.name = 'คอมพิวเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9525' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9527' AND e.name = 'โปรเจกเตอร์';
INSERT INTO room_equipment (room_id, equipment_id, quantity)
SELECT r.id, e.id, 1 FROM rooms r, equipment e WHERE r.code = 'SC09-9527' AND e.name = 'ไวท์บอร์ด';
