-- คนที่ 3: การจอง (N:1 กับ users และ rooms)

CREATE TABLE bookings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    room_id    BIGINT       NOT NULL,
    start_time TIMESTAMP    NOT NULL,
    end_time   TIMESTAMP    NOT NULL,
    purpose    VARCHAR(300) NOT NULL,
    attendees  INTEGER      NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- ไม่ใส่ ON DELETE CASCADE เพราะห้ามลบผู้ใช้หรือห้องที่มีการจองแล้ว ให้ปิดใช้งานด้วย status แทน
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT ck_bookings_time CHECK (end_time > start_time),
    CONSTRAINT ck_bookings_attendees CHECK (attendees > 0),
    CONSTRAINT ck_bookings_status CHECK (status IN
        ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CHECKED_IN', 'COMPLETED', 'NO_SHOW'))
);

-- ใช้ตรวจเวลาชน: ค้นด้วย room_id แล้วเทียบช่วงเวลา
CREATE INDEX idx_bookings_room_time ON bookings (room_id, start_time, end_time);
CREATE INDEX idx_bookings_user ON bookings (user_id);
CREATE INDEX idx_bookings_status ON bookings (status);

-- ===== การจองตัวอย่างสำหรับ Demo (เวลาอิงจากวันที่ migrate) =====

INSERT INTO bookings (user_id, room_id, start_time, end_time, purpose, attendees, status)
SELECT u.id, r.id,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '1' DAY + INTERVAL '9' HOUR,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '1' DAY + INTERVAL '11' HOUR,
       'ติวสอบกลางภาควิชา CP353002', 25, 'PENDING'
FROM users u, rooms r WHERE u.email = 'student@kkumail.com' AND r.code = 'SC09-9226';

INSERT INTO bookings (user_id, room_id, start_time, end_time, purpose, attendees, status)
SELECT u.id, r.id,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '1' DAY + INTERVAL '13' HOUR,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '1' DAY + INTERVAL '16' HOUR,
       'สอนชดเชยวิชา Software Design', 60, 'APPROVED'
FROM users u, rooms r WHERE u.email = 'lecturer@kkumail.com' AND r.code = 'SC09-CP9127';

INSERT INTO bookings (user_id, room_id, start_time, end_time, purpose, attendees, status)
SELECT u.id, r.id,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '2' DAY + INTERVAL '9' HOUR,
       CAST(CURRENT_DATE AS TIMESTAMP) + INTERVAL '2' DAY + INTERVAL '12' HOUR,
       'ปฐมนิเทศนักศึกษาฝึกงาน', 150, 'APPROVED'
FROM users u, rooms r WHERE u.email = 'staff@kkumail.com' AND r.code = 'SC09-CP9127';

INSERT INTO bookings (user_id, room_id, start_time, end_time, purpose, attendees, status)
SELECT u.id, r.id,
       CAST(CURRENT_DATE AS TIMESTAMP) - INTERVAL '1' DAY + INTERVAL '10' HOUR,
       CAST(CURRENT_DATE AS TIMESTAMP) - INTERVAL '1' DAY + INTERVAL '12' HOUR,
       'ประชุมโปรเจกต์กลุ่ม', 5, 'COMPLETED'
FROM users u, rooms r WHERE u.email = 'student2@kkumail.com' AND r.code = 'SC09-9231';

INSERT INTO bookings (user_id, room_id, start_time, end_time, purpose, attendees, status)
SELECT u.id, r.id,
       CAST(CURRENT_DATE AS TIMESTAMP) - INTERVAL '2' DAY + INTERVAL '14' HOUR,
       CAST(CURRENT_DATE AS TIMESTAMP) - INTERVAL '2' DAY + INTERVAL '15' HOUR,
       'อ่านหนังสือกลุ่ม', 4, 'NO_SHOW'
FROM users u, rooms r WHERE u.email = 'student@kkumail.com' AND r.code = 'SC09-9428';
