-- คนที่ 4: ประวัติการเปลี่ยนสถานะการจอง (N:1 กับ bookings)

CREATE TABLE booking_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT      NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20) NOT NULL,
    changed_by  BIGINT,
    note        VARCHAR(500),
    changed_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- ลบการจองที่ยัง PENDING แล้วประวัติถูกลบตาม
    CONSTRAINT fk_history_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    -- changed_by เป็น NULL ได้ หมายถึงระบบเปลี่ยนเอง (scheduler)
    CONSTRAINT fk_history_changed_by FOREIGN KEY (changed_by) REFERENCES users (id)
);

CREATE INDEX idx_history_booking ON booking_status_history (booking_id, changed_at);

-- ประวัติเริ่มต้นของการจองตัวอย่างใน V3
INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note, changed_at)
SELECT b.id, NULL, 'PENDING', b.user_id, 'สร้างการจอง', b.created_at FROM bookings b;

INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note, changed_at)
SELECT b.id, 'PENDING', 'APPROVED', u.id, 'อนุมัติ', b.created_at
FROM bookings b, users u
WHERE b.status IN ('APPROVED', 'COMPLETED', 'NO_SHOW') AND u.email = 'staff@kkumail.com';

INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note, changed_at)
SELECT b.id, 'APPROVED', 'CHECKED_IN', b.user_id, 'check-in', b.start_time
FROM bookings b WHERE b.status = 'COMPLETED';

INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note, changed_at)
SELECT b.id, 'CHECKED_IN', 'COMPLETED', NULL, 'ระบบปิดการจองเมื่อเลยเวลาสิ้นสุด', b.end_time
FROM bookings b WHERE b.status = 'COMPLETED';

INSERT INTO booking_status_history (booking_id, from_status, to_status, changed_by, note, changed_at)
SELECT b.id, 'APPROVED', 'NO_SHOW', NULL, 'ไม่ check-in ภายใน 15 นาทีหลังเวลาเริ่ม', b.start_time + INTERVAL '15' MINUTE
FROM bookings b WHERE b.status = 'NO_SHOW';
