-- คนที่ 5: การแจ้งเตือนในระบบ (N:1 กับ users)

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    booking_id BIGINT,
    type       VARCHAR(30)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- ลบการจอง (PENDING) แล้วแจ้งเตือนยังอยู่ แค่ไม่ผูกกับการจองแล้ว
    CONSTRAINT fk_notifications_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE SET NULL,
    CONSTRAINT ck_notifications_type CHECK (type IN
        ('BOOKING_CREATED', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'BOOKING_CANCELLED', 'BOOKING_NO_SHOW'))
);

-- ใช้นับจำนวนที่ยังไม่อ่านของผู้ใช้ (กระดิ่งแจ้งเตือน)
CREATE INDEX idx_notifications_user_read ON notifications (user_id, is_read);
CREATE INDEX idx_notifications_booking ON notifications (booking_id);

-- แจ้งเตือนตัวอย่างของการจองใน V3
INSERT INTO notifications (user_id, booking_id, type, message, is_read)
SELECT u.id, b.id, 'BOOKING_CREATED', 'มีคำขอจองห้อง SC09-2203 รออนุมัติ', FALSE
FROM users u, bookings b, rooms r
WHERE u.email = 'staff@kkumail.com' AND b.room_id = r.id AND r.code = 'SC09-2203' AND b.status = 'PENDING';

INSERT INTO notifications (user_id, booking_id, type, message, is_read)
SELECT b.user_id, b.id, 'BOOKING_NO_SHOW', 'การจองห้อง SC09-4402 ถูกบันทึกว่าไม่มาใช้ห้อง', FALSE
FROM bookings b, rooms r
WHERE b.room_id = r.id AND r.code = 'SC09-4402' AND b.status = 'NO_SHOW';
